[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "components>=0.0.1a0",
    "networkx>=3.4.2",
    "numpy>=2.2.1",
    "plotly>=5.24.1",
    "scipy>=1.15.1",
    "solana>=0.25.1",
    "solana-sdk>=0.25.6",
    "streamlit>=1.41.1",
]
